services:
    _defaults:
        autowire: true

    Training\Bundle\UserNamingBundle\Integration\NamingTypeChannel:
        tags:
            - { name: oro_integration.channel, type: naming_type }

    Training\Bundle\UserNamingBundle\Integration\NamingTypeTransport:
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@logger'
        tags:
            - { name: oro_integration.transport, type: naming_type, channel_type: naming_type }
